[package]
name = "microtype"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/cameron1024/microtype"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"
