name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (all features)
      run: cargo test --verbose --all-features
    - name: Cargo doc
      run: cargo doc
    - name: Build (macro)
      run: (cd microtype-macro; cargo build --verbose)
    - name: Run tests (macro)
      run: (cd microtype-macro; cargo test --verbose)
    - name: Run tests (all features) (macro)
      run: (cd microtype-macro; cargo test --verbose --all-features)
    - name: Cargo doc (macro)
      run: (cd microtype-macro; cargo doc)
